### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#1]
We want kampus members to be able to share links and have discussions for those links. `Pano` is a platform to solve this problem.

---

- can only post links
- add replies
- replies can have replies
- only publisher members can post links
- username/email/password
- predetermined set of tags
- a post can have many tags
- upvote

---

## tech

- v0
  - amplify
  - gql
  - remix.run

---

- remix.run
- gql
- twirp services
  - post & comments
  - tags
  - users
  -

**Comment by cansirin** [comment]
isDeleted for replies
post & reply edit

**Comment by usirin** [comment]
active - en son comment atilan postlar
recent - most recent posts

**Comment by cansirin** [comment]
user settings
- change password
- delete account

**Comment by cansirin** [comment]
we need share button

**Comment by usirin** [comment]
Needs to be converted into a SPEC.md
