### ISSUE TITLE
add image to meta tags

### ISSUE THREAD

**Issue by cansirin** [kamp-us/monorepo#123]

**Comment by cansirin** [comment]
I'll let you know when a logo link is ready and provide it to you to include in meta tags of post

**Comment by cansirin** [comment]
I uploaded our logo to a S3 bucket. 
SVG: https://kampus-logo.s3.eu-central-1.amazonaws.com/DplcC3sZ_400x400.svg
PNG: https://kampus-logo.s3.eu-central-1.amazonaws.com/DplcC3sZ_400x400.png

**Comment by cansirin** [comment]
Favicon: https://kampus-logo.s3.eu-central-1.amazonaws.com/favicon.ico

**Comment by usirin** [comment]
Fixed with #178
