### ISSUE TITLE
No error message when sending new post

### ISSUE THREAD

**Issue by rasitxy** [kamp-us/monorepo#152]
### Describe the bug

When I try to send a new post, the error message does not appear, even though the inputs are incorrect.

https://www.youtube.com/watch?v=glrAISB2RIU

**Comment by cansirin** [comment]
We can get action/load data from fetcher's data field (fetcher.data) so we can still use fetcher.Form.

This bug will be addressed in my "adding content field to post" PR, so no need to work on this issue.
