### ISSUE TITLE
Fix page not responding after opening post delete dialog

### ISSUE THREAD

**Issue by cansirin** [kamp-us/monorepo#165]
When a user clicks on the "Sil" button for a post, a modal appears to ask the user to confirm or cancel the deletion. However, after the user clicks on either the "Evet" or "Hayır" button in the modal, the page becomes unresponsive. No other actions can be performed on the page until it is refreshed.

## Steps to Reproduce

1. Go to the website and navigate to a page that displays a list of posts.
2. Click on the "Sil" button for any of the posts.
3. In the modal that appears, click on either the "Evet" or "Hayır" button.
4. Observe that the page becomes unresponsive and no further actions can be performed. 

## Expected Behavior

After the user clicks on either the "Evet" or "Hayır" button in the modal, the modal should be closed and the user should be able to continue interacting with the page as normal.

## Actual Behavior

After the user clicks on either the "Evet" or "Hayır" button in the modal, the page becomes unresponsive and no further actions can be performed until the page is refreshed.

**Comment by usirin** [comment]
This issue still needs investigation to figure out what the root cause is. @cansirin said he has some ideas.
