### ISSUE TITLE
safe environment variables

### ISSUE THREAD

**Issue by beyazit** [kamp-us/monorepo#170]
### Describe the feature you would like to see added

Validate access to environment variables and parse them to the right type. Makes sure you don't accidentally deploy apps with missing or invalid environment variables.

### Describe the solution you'd like

we can use [envsafe](https://github.com/KATT/envsafe)

```ts
// utils/env.server.ts
import { envsafe, str, url } from "envsafe";

export const env = envsafe({
	NODE_ENV: str({
		devDefault: "development",
		choices: ["development", "test", "production"],
	}),
        DATABASE_URL: url({
                 devDefault: "postgresql://pgtest:pgtest@postgres:5432/pgtest?schema=public&connect_timeout=300"
        }),
        // ...others
});
```

**Comment by EmirBoyaci** [comment]
We can also do as like in [here](https://dev.to/asjadanis/parsing-env-with-typescript-3jjm) without adding any dependency. I haven't seen "envsafe" before but it looks cool to be honest, but I prefer doing that without adding any dependency.

**Comment by beyazit** [comment]
![Image](https://user-images.githubusercontent.com/79628065/221382499-04738888-ef4e-417c-9bfa-e037b80f236d.gif)
