### ISSUE TITLE
Update the style of title of posts without url

### ISSUE THREAD

**Issue by cansirin** [kamp-us/monorepo#190]

**Comment by EmreKarslan** [comment]
![image](https://user-images.githubusercontent.com/15327343/209026936-d5ea82e4-77fd-4649-bf94-c1956a4a12a7.png)
Do we want post titles to look like that? And when we click on the title redirects us to the Post page. Am I right?

**Comment by cansirin** [comment]
Thanks for your observation! Yes, you're right. Please let me know if you want to work on this. @EmreKarslan

**Comment by EmreKarslan** [comment]
I can work on it.
