### ISSUE TITLE
Comment Expand when coming in with hash in url

### ISSUE THREAD

**Issue by csoylu** [kamp-us/monorepo#194]
### Describe the bug

All the comments expand when we come in from a comment share link, which includes a hash "#".

### Steps to reproduce the behavior

Make sub-comments, take sharing link from one of those comments and use it.

### Expected behavior

Only the parents of the shared comment should expand.

**Comment by csoylu** [comment]
I started working on it already the actual solution i found is:

- Get all the parent id's of the comment that client wants to access using link
$slug-$id.tsx
```js
function getOpenCommentIDs(comment: Comment, visualTree: VisualTree): Set<string> {
  let commentIDs = new Set<string>(comment.parentID);
  if (!comment.parentID) { return commentIDs; }
  commentIDs = new Set([ ...getOpenCommentIDs(visualTree[comment.parentID].comment, visualTree), comment.parentID]);
  
  return commentIDs;
}

...
...
...

  const [expandedIDs, setExpandedIDs] = useState<Set<string>>(new Set<string>());
  useEffect(() => {
    if (expandedID !== ""){
      setExpandedIDs(getOpenCommentIDs(visualTree[expandedID].comment, visualTree));
    }
  }, [expandedID]);
```

- Then we send these id's to the comment items and all comment items check if their id is in this list:
```js
  useLayoutEffect(() => {
    setShowComment(expandedIDs.has(comment.id));
  }, [expandedIDs]);
 ```
 
 
 My only problem is focus and coloring of the target comment.

**Comment by usirin** [comment]
This should be fixed, let's re open if not.
