### ISSUE TITLE
Add a lint GitHub action that runs on a pull request and pushes to the main branch

### ISSUE THREAD

**Issue by OmerFI** [kamp-us/monorepo#203]
### Describe the feature you would like to see added

Adding a lint GitHub action that runs on a pull request and pushes to the main branch could help ensure the quality and consistency of your code.

### Describe the solution you'd like

My work: https://github.com/OmerFI/monorepo/commit/90f883e5a3a742ddc4fdfce97497cdfa2588a6c4

**Comment by usirin** [comment]
@OmerFI Thank you so much for starting this discussion. I'd like all of us in the same page when we are introducing a crucial infra like this. 

So can we first talk about this here: 
- what steps we are going to introduce to the pipeline?
- links to some sort of documentation for each step.
- Also why we are introducing each step, what problem does it solve?
