### ISSUE TITLE
Comment orders

### ISSUE THREAD

**Issue by csoylu** [kamp-us/monorepo#204]
### Describe the bug

Comments are ordered weirdly under a post. Whenever I edit a comment, the order changes. I couldn't find any sorting in the project right now.

### Steps to reproduce the behavior

Make several comments, edit some and play around.

### Expected behavior

I think that comments should be ordered, maybe a button with which we can choose between **most upvotes** and **by time**.

**Comment by csoylu** [comment]
The sort button might be situated here: 
![image](https://user-images.githubusercontent.com/94180156/208962791-e70cec71-8455-4206-8e98-a38684e825cf.png)

**Comment by usirin** [comment]
We want to sort on db fetch time: https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sorting

**Comment by csoylu** [comment]
Do we want to sort this chronologically or by most upvotes?

**Comment by csoylu** [comment]
created@ allright: got from twitch :)
