### ISSUE TITLE
Comment | Post divider

### ISSUE THREAD

**Issue by csoylu** [kamp-us/monorepo#206]
### Describe the feature you would like to see added

When we open the post page, the posts and comments seem a bit blended.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

A subtle divider placed on the red areas:
![image](https://user-images.githubusercontent.com/94180156/208962413-1e46c119-2acf-4cbb-a152-b735f68f785b.png)

### Describe alternatives you have considered

Change divider spaces or styles, or use different colors for different sections of the page.

**Comment by enesinan** [comment]
I can fix that issue @usirin
