### ISSUE TITLE
Unify comment components

### ISSUE THREAD

**Issue by burakcan** [kamp-us/monorepo#210]
### Describe the feature you would like to see added

There are a couple of different implementations of the comment textarea. To fix a bug or improve the commenting experience; you'd need to duplicate the changes across these competing implementations. 
Making it a single shared component would simplify things.

**Comment by MhmtMutlu** [comment]
As I understand that there are several comment component or implementation and you want to unify them as single component. If you give me more information, I would like to fix and contribute to this project.

**Comment by cansirin** [comment]
Hello @MhmtMutlu 

Thank you for your interest to the project.  We encourage you to check out the open issues that are not marked as needing triage, and consider contributing to those if you are interested in helping out with the project. If you can't find one, can you please join our discord server and ask questions from there? So we can triage the issue and assign it to you that way.

**Comment by MhmtMutlu** [comment]
Hello @cansirin 

Thank you for your quick response. I will check other issues on GitHub. Besides, I have already joined discord, but I could not find time to check all channels. Would you tell me that which channel should I follow to observe issues? Also, I am not indifferent to the subject. I have been trying to follow all streams in twitch.

**Comment by cansirin** [comment]
We are using #kampus-projects channel for anything related with kampus projects. 

It is happy to see you here and ready to contribute to the projects!

**Comment by cansirin** [comment]
We are using two different <Textarea> components in `Comment.tsx` and `EditCommentForm.tsx`. We need to create a new component which responsible of comment text area. With this, we will be able to have same functionality while adding and/or editing comments.
