### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by EmreKarslan** [kamp-us/monorepo#212]
### Describe the feature you would like to see added

Currently, our project relies on test users that are created through scripts for testing and development purposes. However, as we move towards a live deployment, we recognize the need to add a sign-up feature to the project to allow users to create their own accounts. This will enhance the user experience and allow us to better serve the needs of our users by providing them with a convenient and intuitive way to create and manage their own accounts. We believe that adding a sign-up feature to the project is an important step in its evolution and will help to ensure its long-term success.

### Describe the solution you'd like

Currently, our project has a database query that is used to create new user accounts. However, we do not have a dedicated page or interface for users to sign up for an account. To improve the user experience and make it easier for users to create new accounts, we propose adding a sign-up page to the project. This page would be similar in function to the existing sign-in page, with the necessary elements such as forms for entering personal information, selecting a username and password, and agreeing to terms and conditions. By adding a sign-up page, we can provide users with a clear and intuitive path to creating their own accounts and make it easier for them to start using our product or service.

**Comment by usirin** [comment]
Agreed, we need to talk to the kampus-bot team and sync with them, we initially wanted the registration to be only with the kampus discord bot to make sure we only get signups from the community. Thanks for creating this issue. We, at least, need to make a decision.

**Comment by usirin** [comment]
cc @cansirin @durmusrasit

**Comment by usirin** [comment]
This is getting done by remix-auth solution atm. So i'll close this for now, we can re-open if we think we need to work on it more.
