### ISSUE TITLE
Fix url generated for comment & post share links

### ISSUE THREAD

**Issue by cansirin** [kamp-us/monorepo#238]
Urls used to be `slug-id` but we changed to `slug/id` format. We need to create a new util under the post/comment feature that creates urls for posts and comments.

- [ ] add a new util to generate this url for us using the post model.

**Comment by sinirzi** [comment]
I can handle this issue.

**Comment by cansirin** [comment]
Why did we reopen this issue?

**Comment by durmusrasit** [comment]
A function will be created where we can edit the URL string from one place.

**Comment by usirin** [comment]
@cansirin this is not yet fixed for every post link.
