### ISSUE TITLE
rookie system similar to eksisozluk

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#239]

**Comment by puskuruk** [comment]
Will we only have `rookie` and `author`? And what are the requirement to be an `author`? Will we use the same approach with eksi? If I remember correctly user needs to have 10 verified post to become an `author`. If we'll follow the same approach we'll need to have `isVerified` or something similar in posts table

**Comment by usirin** [comment]
Closing this for now to focus on a contribution ready mvp.
