### ISSUE TITLE
When pano was launched for the first-time, recent posts did not work as expected when sorting posts

### ISSUE THREAD

**Issue by durmusrasit** [kamp-us/monorepo#247]
### Describe the bug

Most recent posts feature did not sort posts by recent activities when pano was launched for the first time.

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. Create a few new post
2. Create a new comment into one of it
3. Sort posts by recent activity

### Expected behavior

Expect to see the oldest posts appear at the top

**Comment by usirin** [comment]
@cansirin any ideas?

**Comment by cansirin** [comment]
I have to investigate this issue, no idea.

**Comment by ikadgzl** [comment]
Yes, it's becuase 
```
  comments: {
        orderBy: {
          createdAt: "desc", // this is changed
        },
        include: {
          owner: true,
          upvotes: true,
        },
      },
      _count: {
        select: { comments: true },
      },
    },
// below is needed
    orderBy: {
      createdAt: "desc",
    },
```

should be added to post itself if the expected behaviour is both _post create date_  and _posts' comment date_ descending, which makes sense in terms of "activeness" of posts.

I've fixed it, waiting for a permission to push it in a new branch and make a PR req.

**Comment by durmusrasit** [comment]
You can fork this repo and create a branch in it, then send a pr request with that branch.
