### ISSUE TITLE
About count of child comments in nested comment section

### ISSUE THREAD

**Issue by arabacibahadir** [kamp-us/monorepo#270]
### Describe the bug

The comment section currently displays an inaccurate count of child comments in the nested section. For example, it shows "(1 comment)" instead of "(2 comments)" even though there are two child comments under the parent comment.

### Steps to reproduce the behavior

1. Go to any post which has nested comments
2. Click "Göster"
![image](https://user-images.githubusercontent.com/32988819/222990640-f21ba3ed-9c16-42ee-998a-3aeaca450c23.png)
3. The nested comment section currently shows that there is one more nested comment, but the count for the first parent comment only displays "(1 yorum)". The parent comment count should be to reflect the actual number of comments, which is "(2 yorum)".
![image](https://user-images.githubusercontent.com/32988819/222990670-61132dfc-2f44-4f01-8317-ecda10d08730.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/32988819/222991189-8a483e77-79ac-4d3d-8fd9-f224a210270a.png)

**Comment by cansirin** [comment]
Thanks for creating this issue! 

Actually this is expected behavior because even though first child (2) has another comment, that comment is made for that specific first child (2) comment which means first parent has only 1 comment on itself.

**Comment by arabacibahadir** [comment]
I assumed that all comment counts would be displayed. Thank you for explaining the expected behavior.
