### ISSUE TITLE
Subcomment section closes when clicking `Cevapla` button without a comment

### ISSUE THREAD

**Issue by durmusrasit** [kamp-us/monorepo#283]
### Describe the bug

Subcomment section closes when clicking `Cevapla` button without filling the comment section

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. Go to any post
2. Click the `Cevapla` button on any sub-comment without filling the comment section

### Expected behavior

Subcomment section closes instantly

**Comment by arabacibahadir** [comment]
Here's the video I took when I repeated this error:

https://user-images.githubusercontent.com/32988819/223156411-5962f10e-8f7d-4b66-a254-ce7ddfb35d05.mp4
