### ISSUE TITLE
"begenilenler" should be "en begenilenler" in the sorting options

### ISSUE THREAD

**Issue by cansirin** [kamp-us/monorepo#286]
in `PostSorter` component we need to change this "begenilenler" title to "en begenilenler"

**Comment by puskuruk** [comment]
Also, we should have a time frame for the most popular posts. If Hacker News used our strategy, we would be seeing React.js' announcement post in the most popular posts tab.

**Comment by cansirin** [comment]
> Also, we should have a time frame for the most popular posts. If Hacker News used our strategy, we would be seeing React.js' announcement post in the most popular posts tab.

Even though I agree with this, let's capture anything related this under another issue. I'll create one and link it here. Thanks for the suggestion!

**Comment by Murat-tunca** [comment]
ok i will fix it
