### ISSUE TITLE
bug: username collision on registration when remix-auth providers are used

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#318]
### Describe the bug

Right now a user can register and change their username to be an email that they don't own, and that would prevent a regular registration with that email.

### Problem:
- Current implementation populates username field with the email value we get from remix-auth providers.
- This creates the problem described in the scenario

#### Scenario:
- umut creates an account with an email: `umut@umut.co`
- umut goes to account settings and changes his username to: `cansirin@kamp.us` but keeps his email the same: `umut@umut.co`
- can tries to create an account with an email: `cansirin@kamp.us`
- we return an error saying that we have a user with that username.

### Expected behavior

We need to find a way to not use emails for default values for usernames :D

**Comment by andyanday33** [comment]
We could try to store both the username and email as NAME@PROVIDER, this would ensure that both the fields are unique for each provider, and since we know the type of all the possible providers, it should not be hard to query these fields afterwards.

**Comment by andyanday33** [comment]
We could try adding randomly generated numbers after the username if the username is not available.
For example:
- umut creates an account with an email: umut@umut.co
- umut goes to account settings and changes his username to: cansirin@kamp.us but - - keeps his email the same: umut@umut.co
- can tries to create an account with an email: cansirin@kamp.us
- can's newly created account has the name cansirin123 (or some other random value)
