### ISSUE TITLE
Bug: random suffix addition on username generation adds floating numbers instead of integers

### ISSUE THREAD

**Issue by andyanday33** [kamp-us/monorepo#328]
### Describe the bug

Random suffix adition on username creation if the username already exists, adds a floating point number like 4452.35252 to the username.

### Steps to reproduce the behavior

- A user creates an account with the email address `umut@kamp.us`, his username is generated as `umut`
- `umut` changes his username to `bilbo`
- Another user tries to create an account with the email address `bilbo@middle.earth`
- The username generated for bilbo would be `bilbo3452.1124325`

### Expected behavior

We would probably just want to keep the integer part of the suffix and throw the rest.
After step 3, bilbo's generated username should be `bilbo3452`

**Comment by mertsabinov** [comment]
LGTM
