### ISSUE TITLE
feat:  If users are not logged in, they may be redirected to the login page when they click the upvote button.

### ISSUE THREAD

**Issue by mertsabinov** [kamp-us/monorepo#336]
### Describe the feature you would like to see added

I would like to see a feature added where if a user who is not logged in clicks the upvote button, they are redirected to the login page to authenticate themselves before being able to upvote the content.

### Describe alternatives you have considered

-

### Additional context

It can encourage users who have not yet signed in to create an account or sign in to their existing account, which can increase user engagement and retention on the platform. Currently, when a non-logged-in user clicks the upvote button, they are unable to upvote the content and there is no redirect or prompt to the login page.

**Comment by cansirin** [comment]
This sounds like a great feature to have! 🚀
