### ISSUE TITLE
Persist dark/light mode option

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#34]
**Title:** Persist dark/light mode settings per user

**Description:**
We want to be able to persist the dark/light mode setting for each user in our web project. Currently, we have a users service that allows us to store user-specific settings, so we can use this to store the dark/light mode setting for each user.

To implement this, we will need to add a new field to the user's settings to store the dark/light mode preference. This preference should be saved whenever the user switches between dark and light mode in the application.

Once the preference is saved, we can use it to automatically apply the correct mode when the user logs in to the application.

**Suggested Implementation:**
1. Add a new field to the user's settings to store the dark/light mode preference (e.g. `dark_mode_enabled`).
2. Whenever the user switches between dark and light mode in the application, save the preference in the user's settings.
3. When the user logs in to the application, check their settings and apply the correct mode based on their preference.

**Additional Considerations:**
- We should also provide a way for the user to manually override the default mode if they want to use a different mode for a specific session.
- We should consider how to handle users who have not saved a preference, and whether we want to use a default mode for these users.

**Comment by ozhanefemeral** [comment]
ozzy 🦆
