### ISSUE TITLE
bug(apps/pano): light theme preference not retained after page refresh

### ISSUE THREAD

**Issue by sametkayik** [kamp-us/monorepo#361]
### Describe the bug

When the page is refreshed after selecting the light theme, it reverts back to the default dark theme. 

Theme preferences are not persisting for guest and logged-in users in the production environment. However, in the development environment, the theme preference for the admin test account is remembered, but there is a delay in loading the selected theme.

In production, the user's preferred theme does not remain.

![pano-theme-update](https://user-images.githubusercontent.com/53970699/229358879-792f53f2-1b32-4e49-a2b3-6e6127952977.gif)

Local admin user's theme delayed on refresh.

![pano-theme-update-admin](https://user-images.githubusercontent.com/53970699/229358914-1bf88a20-5922-4385-b21f-8e4442478587.gif)

### Steps to reproduce the behavior

1. Click to change the theme button.
2. Refresh the page and observe theme is not retained.

### Expected behavior

The selected theme preference should be retained and persist across page refreshes for all users, including guests and logged-in users.

**Comment by andyanday33** [comment]
Apparently #369 did not resolve this problem, I will open up a new PR regarding this

**Comment by usirin** [comment]
oh damn, what is the issue then? do you have any ideas?

**Comment by usirin** [comment]
can it be because there was a deployment failure? 🤔 let me see.

**Comment by usirin** [comment]
Closing this as we will redo pano.
