### ISSUE TITLE
bug(apps/pano): Inconsistent Margins on Header Menu between home and login pages

### ISSUE THREAD

**Issue by UgurKacak** [kamp-us/monorepo#364]
### Describe the bug

Description: There is an inconsistency with the margins on the header menu between the landing page (https://pano-dev.fly.dev/) and the login page (https://pano-dev.fly.dev/login). This can be observed when transitioning between the two pages.

![bug](https://user-images.githubusercontent.com/12225104/230682425-8cb54c50-b4d2-42e9-9729-c696d794c997.png)

### Actual Result
The header menu has different margins on the landing page and login page

### Possible Solution
Adjust the margins of the header menu to be consistent across both pages.

### Steps to reproduce the behavior

1. Go to https://pano-dev.fly.dev/
2. Click on the "Log in" button on the top right corner
3. Observe the header menu during the transition between the two pages
4. Expected result: The header menu should have consistent margins on both pages

### Expected behavior
The header menu should have consistent margins on both pages

**Comment by UgurKacak** [comment]
When running the development branch locally, no issues appear. :smiley:

**Comment by cansirin** [comment]
I didn't do a deep dive but what i have in my mind is; we have lots of posts in dev environment and this causes scrollbar to appear and makes screen move. This doesn't happen in local because we have a limited amount of posts.

**Comment by cansirin** [comment]
I'm closing this since this isn't really a big much of problem for now. We'll consider opening a new one if this becomes unbearable.
