### ISSUE TITLE
bug(apps/pano): social login button titles are spilt over the button borders on mobile web

### ISSUE THREAD

**Issue by gunesmert** [kamp-us/monorepo#372]
### Describe the bug

![IMG_1187](https://user-images.githubusercontent.com/5896611/231819159-d4b145f3-972f-4618-bb97-90b2126790ce.PNG)

### Steps to reproduce the behavior

1. Open login page on a mobile web browser (in my case it was Safari on iPhone)
2. Observe that social login button titles are spilt over the button borders

**Comment by usirin** [comment]
Expected behavior:
- move buttons to their own lines for mobile web
- do not render them on the same line

**Comment by akselsaatci** [comment]
Should i use stiches's media queries to solve this problem ?
Stiches responsive style docs: https://stitches.dev/docs/responsive-styles

**Comment by usirin** [comment]
@akselsaatci this sounds like a great plan, please check our theme under `packages/kampus-ui` and let's add some breakpoints there so we can use them in our apps as well.
