### ISSUE TITLE
feat: migrate shadcn for ui components

### ISSUE THREAD

**Issue by cansirin** [kamp-us/monorepo#412]
- [x] [AlertDialog.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/AlertDialog.tsx)
- [x] [Avatar.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Avatar.tsx)
- [x] [ControlGroup.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/ControlGroup.tsx) - Custom component
- [x] [Dialog.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Dialog.tsx)
- [x] [Dropdown.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Dropdown.tsx)
- [ ] [ExternalLink.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/ExternalLink.tsx)
- [ ] [IconButton.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/IconButton.tsx)
- [x] [Input.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Input.tsx)
- [ ] [InternalLink.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/InternalLink.tsx)
- [x] [Label.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Label.tsx)
- [ ] [Link.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Link.tsx)
- [ ] [OAuthProviderLogo.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/OAuthProviderLogo.tsx)
- [x] [Select.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Select.tsx)
- [x] [Separator.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Separator.tsx)
- [ ] [SocialMediaButtons.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/SocialMediaButtons.tsx)
- [ ] [Text.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Text.tsx)
- [x] [Textarea.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Textarea.tsx)
- [ ] [ThemeToggle.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/ThemeToggle.tsx)
- [ ] [Timeago.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Timeago.tsx)
- [x] [Toast.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/Toast.tsx)
- [ ] [UserAvatar.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/UserAvatar.tsx)
- [ ] [ValidationMessage.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/ValidationMessage.tsx)
- [x] [Button.tsx](https://github.com/kamp-us/monorepo/blob/dev/packages/kampus-ui/src/layout-components/Button.tsx)

**Comment by cansirin** [comment]
I'm taking care of this

**Comment by Ketcap** [comment]
@cansirin I'm here as an assignee to assit on reviews let me know if you require anything from me.

**Comment by cansirin** [comment]
> @cansirin I'm here as an assignee to assist on reviews let me know if you require anything from me.

Thanks a lot for the support you are showing so far! I updated my PR #501  for the last components, we may need to create another issue to include them into the storybook after we merge it
