### ISSUE TITLE
(apps/pano) Issue with seeding DB

### ISSUE THREAD

**Issue by mscankat** [kamp-us/monorepo#419]
### Describe the bug

DB is not seeded automatically with the instructions given in the related README.md's. Also I have an issue about seeding DB with the provided seed.ts file manually. 

### Steps to reproduce the behavior

- Clone the repo
- Install Volta
- At the root path run following commands:
    - `npm install`
    - `npx turbo build`
- head to __/pano__ directory
- create .env file from example : `cp .env.example .env`
- start DB with docker: `docker-compose up --build`
- run `npm run dev`
- Open the local server on your browser and you can see there is no posts nor you can login with supposedly seeded data.

### Expected behavior

There should be initial posts and user credentials that are supposedly seeded with __/db/pano-prisma/prisma/seed.ts__ file.

**Comment by usirin** [comment]
Repo is going through a big overhaul atm. when they are done, we'll update the readme as well.
