### ISSUE TITLE
add user management routes under `/pasaport` for pasaport.kamp.us

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#450]
https://pano-dev.kamp.us/settings type of pages will be hosted under `/pasaport` route and will be served as `pasaport.kamp.us`

**Comment by Ketcap** [comment]
@usirin I'm assuming all the apps using authentication should share this page to account settings. Is that a correct assumption?
Would you like me to create a page for this after #457 ?

**Comment by usirin** [comment]
@Ketcap i am sorry, i've missed this. we talked about this on stream today and decided to move forward with the plan @Ketcap decided above.

**Comment by Ketcap** [comment]
No worries @usirin , i'll lay down the plan for this and create more tasks and split into chunks as we spoke

**Comment by Ketcap** [comment]
Sub pages added for future tasks see https://github.com/kamp-us/monorepo/discussions/526
