### ISSUE TITLE
feat: add next-auth config & use it in necessary apps

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#457]
### Describe the feature you would like to see added

- we will create a new package called `@kampus/next-auth` under `packages/next-auth`
- This will export the next-auth configuration we will use in our next.js powered applications. (example: https://github.com/t3-oss/create-t3-turbo/tree/main/packages/auth)
- all auth related routes needs to be grouped under `kamp.us/pasaport` route.
- We will start with 3 providers:
  - Email
  - Github
  - Discord
  - Bonus: Twitch

**Comment by Ketcap** [comment]
#459 solves this
