### ISSUE TITLE
@kampus/sozluk-content build gives error 

### ISSUE THREAD

**Issue by alicangunduz** [kamp-us/monorepo#477]
### Describe the bug

When running `npx turbo build` on Windows, I encountered an error from the `@kampus/sozluk-content package` . The error message was: 🥲 ( ˘︹˘ )

It seems that the error is related to the `@kampus/sozluk-content` package during the build process. This package might be causing compatibility issues with the Windows operating system.

### Steps to reproduce the behavior

1. Make sure you have the latest version of Node.js and npm installed on your Windows machine.
2. Check if there are any known issues or compatibility problems with the `@kampus/sozluk-content` package by visiting its GitHub repository or documentation.
3. Verify that all the required dependencies for the `@kampus/sozluk-content` package are installed correctly.
4.Check if there are any specific configuration settings or environment variables needed for the package to work properly on Windows.
5. If the error persists, you can try reaching out to the package maintainer or the community for support. They might be able to provide more specific guidance or a potential fix for the issue you are facing.

By following these steps, you should be able to troubleshoot and resolve the error you encountered when running `npx turbo build` with the `@kampus/sozluk-content` package on Windows.

![image](https://github.com/kamp-us/monorepo/assets/54004830/37c2548d-802a-4a12-a918-6c6b609d05ae)

### Expected behavior

Things should work normally under windows

**Comment by Ketcap** [comment]
@alicangunduz Thanks for creating the issue couple things I need from you to help on this.

Let me know your packages versions such as node and npm by running
```
npm -v
node -v
```

**Comment by alicangunduz** [comment]
Npm :  9.5.0
Node : v18.14.2

Adjusted with Volter


> @alicangunduz Thanks for creating the issue couple things I need from you to help on this.
> 
> Let me know your packages versions such as node and npm by running
> 
> ```
> npm -v
> node -v
> ```

**Comment by Ketcap** [comment]
@alicangunduz I was not able to reproduce the error, can you check where you are runing the command and make sure you are running on root of the monorepo. 
Keep that in mind that ContentLayer has warning for windows so it might be connected to that.
`Warning: Contentlayer might not work as expected on Windows`

**Comment by alicangunduz** [comment]
@Ketcap Can you specify the root directory address, I want to confirm ?

**Comment by Ketcap** [comment]
@alicangunduz root directory is the base directory of the repo "your/path/to/repo/kampus" so kampus is the root
