### ISSUE TITLE
bug: pasaport login is not working

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#504]
### Describe the bug
When we try to login via postaci using https://pasaport.dev.kamp.us/auth/signin it tries to redirect us to `/api/auth/callback/postaci` instead of `/auth/callback/postaci`

**Comment by Ketcap** [comment]
@usirin Did you try to add "NEXTAUTH_URL" as a `.env` variable. Next-auth uses that to define URLs

**Comment by usirin** [comment]
@Ketcap yep, i also thought that would be the reason but setting it to `NEXTAUTH_URL=https://pasaport.dev.kamp.us/auth` didn't help. I am gonna double check it again.

**Comment by Ketcap** [comment]
@usirin Can we check the "env" file for if there's a default or similar output.  
https://next-auth.js.org/deployment mentioneds about the "NEXTAUTH_URL" but if it's set like this then we can redeploy to see if env applied correctly or not.

**Comment by Ketcap** [comment]
![Screenshot 2023-07-07 at 10 39 31](https://github.com/kamp-us/monorepo/assets/7689820/979aacc1-f4b6-4da3-a21a-a3923de5cec7)
I'm guessing exposing system variable is overwriting the value that we have, investigating more still
https://next-auth.js.org/configuration/options#nextauth_url

**Comment by Ketcap** [comment]
@usirin When i disable expose system envs it worked i'll work on adding this on preview deployments so we can test.

**Comment by Ketcap** [comment]
@usirin Right now the pasaport project on vercel has now disabled on exposing system env variables. That setting overwrites the "NEXTAUTH_URL". latest deployment should not have that variable

**Comment by Ketcap** [comment]
Right now Login works as expected since "/" is empty you cannot see anything there. 👍 I'll start listing issues and working on it.

I'm closing issue since it's resolved
