### ISSUE TITLE
SearchInput autocomplete

### ISSUE THREAD

**Issue by cangnss** [kamp-us/monorepo#92]
### Describe the bug

Background turns white when input autocomplete is done

**Comment by cangnss** [comment]
![ss](https://user-images.githubusercontent.com/20370211/195672254-ef9f2300-1e15-4cf0-9edb-cb1213cc3865.PNG)

**Comment by usirin** [comment]
@cangnss did you start working on this or is this just a report?

**Comment by cangnss** [comment]
No, i didn't start working. Just a report. But I can work on this.

**Comment by usirin** [comment]
No worries, i just wanted to make sure that we don't have duplicate work from different people.

**Comment by cangnss** [comment]
I see. No problem

**Comment by wwardaww** [comment]
Do you know if this issue is still active? I can't reproduce @UgurKacak
